### ISSUE TITLE
module 'tensorflow.contrib' has no attribute 'learn'

### ISSUE THREAD

**Issue by manjubsavanth** [AbrahamSanders/seq2seq-chatbot#10]
Traceback (most recent call last):
  File "chat.py", line 36, in <module>
    model_dir = model_dir) as model:
  File "C:\Users\Manjunatha.Rao\Desktop\Chatbot\seq2seq-chatbot-master\seq2seq-chatbot\chatbot_model.py", line 64, in __init__
    tf.contrib.learn.ModeKeys.validate(self.mode)
AttributeError: module 'tensorflow.contrib' has no attribute 'learn'

**Comment by AbrahamSanders** [comment]
Hey @manjubsavanth

What version of tensorflow do you have installed? Try upgrading to the latest:

pip install --upgrade tensorflow
Or
pip install --upgrade tensorflow-gpu

Regards,
Abraham

**Comment by manjubsavanth** [comment]
Hi Abraham, 

I have upgraded the package, it is working now. Thanks for your response.

**Comment by AbrahamSanders** [comment]
Great!
