### ISSUE TITLE
Train.py not working on Windows 10

### ISSUE THREAD

**Issue by lev4ukpavel2** [AbrahamSanders/seq2seq-chatbot#14]
I am trying to launch training, but I get this:
https://pastebin.com/v5yxALRn
I tried running tensorflow 1.12.0, 1.7.0, 1.6.0 and 1.5.0. I get the same error on every version. Could you help me please?

**Comment by lev4ukpavel2** [comment]
Oh well, it randomly worked. Maybe I just forgot to save hyperparameter's file... You can close this

**Comment by AbrahamSanders** [comment]
@lev4ukpavel2 Awesome! Glad it's working now.
