### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by halilural** [AbrahamSanders/seq2seq-chatbot#26]
Hi All,

When I run the chat_console_best_weights_training.bat, the program gives error like below.

ModuleNotFoundError: No module named 'tensorflow.contrib'

I researched it, and I gave a decision for it, I kindly suggest that you wrote pip upgrade tensorflow, 
but after 2.0 version of tensorflow, 'contrib' version is removed from lib. 

Could you help me for this issue? 

Best Reggards.

**Comment by AbrahamSanders** [comment]
Hi @halilural - Thanks for pointing this out. The project only works with TF 1.x line for now. I will update the readme accordingly.
