### ISSUE TITLE
tf.contrib.learn.ModeKeys.validate(self.mode) AttributeError: type object 'ModeKeys' has no attribute 'validate'

### ISSUE THREAD

**Issue by NitinSaini18** [AbrahamSanders/seq2seq-chatbot#35]
Hi, I am trying to run your model in system from the references of Kirill Eremenko & Hadelin de Ponteves Deep NLP Udemy course
I am facing this error :
Traceback (most recent call last):
  File "chat.py", line 43, in <module>
    model_dir = model_dir) as model:
  File "C:\Users\Lenovo\Documents\seq2seq-chatbot\seq2seq-chatbot\chatbot_model.py", line 71, in __init__
    tf.contrib.learn.ModeKeys.validate(self.mode)
AttributeError: type object 'ModeKeys' has no attribute 'validate'

my tensorflow version is also same as mentioned.
 tf.__version__
Out[2]: '1.0.0'
could you please suggest some way how to solve it.

**Comment by AbrahamSanders** [comment]
This is a different model from the one Hadelin coded in the course. His uses TF 1.0, this one uses TF 1.5+ or higher.

**Comment by NitinSaini18** [comment]
Thank you so much it is solve now.

**Comment by NitinSaini18** [comment]
Hi sir, I am making one website related to travel & tourism using Django and I want to add a chatbot to my website. and when I google it shows me lots of chatbot making websites. I don't want to use those websites. I have made one of my own chatbot using PyTorch. What I want to know from you is how can I add my own trained chatbot to my website.

**Comment by AbrahamSanders** [comment]
You would need to host your bot as an API and call it from your website code. There are many ways to do that and the best approach really depends on the platform you are using to develop your website. At the most basic level you could use something like Flask and Flask-RESTful to create an API that serves your model.
